### ISSUE TITLE
Several issues on running SCRepair

### ISSUE THREAD

**Issue by sunbeomso** [xiaoly8/SCRepair#2]
Thanks for the answer in https://github.com/xiaoly8/SCRepair/issues/1.

However, I still have problems on running SCRepair. Could you help me to run SCRepair?

**[Q1] How to resolve the error message below?**
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/sunbeom/SCRepair/CLI.py", line 4, in <module>
    from .IN import ProblemDetector, RepairCore, DetectedVulnerability, RepairTarget_Detector_Target, RepairTarget_Detector_Target_Remaining, RepairTarget_Detector_Target_Repaired, RepairTarget
ImportError: attempted relative import with no known parent package

```

I got this error message when I ran command ``python3.8 CLI.py repair test.sol``.

**[Q2] Are detectors (Oyente and Slither) expected to be installed using docker images?**

I ask this question because the code in ``Slither.py`` seems to use Slither's docker image.
If not, on which program paths should these detectors be installed?

**[Q3] Could you please provide more detailed instructions or examples on running SCRepair?**

What values should be passed to the ``--detector`` flag?
(e.g., --detector Oyente?, --detector oyente?, or --detector Oyente_docker_container_ID?)

What values should be passed to the ``--targeted_vul`` flag?
(e.g., --targeted_vul integer_overflow?, --targeted_vul integeroverflow? or --targeted_vul IO?)

**Comment by mojtaba-eshghie** [comment]
Hi @SunBeomSo
Replacing all imports in the following form
`form .module_name import some_object`
with:
`import module_name`
and then replace all occurrences of `some_object` with `module_name.some_object` solved this issue for me.
