### ISSUE TITLE
KeyError: 'slither-docker-image'

### ISSUE THREAD

**Issue by mojtaba-eshghie** [xiaoly8/SCRepair#9]
The command used:
`python3 CLI.py --targetContractName 3_.sol repair 3.sol`

Results in the following error:

`Traceback (most recent call last):
  File "CLI.py", line 173, in <module>
    main()
  File "CLI.py", line 136, in main
    loop.run_until_complete(task)  # To process the cancel request
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "CLI.py", line 129, in main
    loop.run_until_complete(waitTask)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/lib/python3.8/asyncio/tasks.py", line 494, in wait_for
    return fut.result()
  File "CLI.py", line 150, in repair
    repairCore = CR.CR((), (),
  File "/home/mojtaba/contracts/SCRepair/CR.py", line 212, in __init__
    super().__init__((Slither.Slither, ETC.ETC), (SolidityM.SolidityM, ),
  File "/home/mojtaba/contracts/SCRepair/IN.py", line 287, in __init__
    self.problemDectors = self.instantiateProblemDectors(
  File "/home/mojtaba/contracts/SCRepair/IN.py", line 317, in instantiateProblemDectors
    return {
  File "/home/mojtaba/contracts/SCRepair/IN.py", line 317, in <dictcomp>
    return {
  File "/home/mojtaba/contracts/SCRepair/IN.py", line 319, in <genexpr>
    for pd in (clsPd(args=detectorArgs) for clsPd in clsProblemDectors)
  File "/home/mojtaba/contracts/SCRepair/Slither.py", line 44, in __init__
    self.docker_image = args['slither-docker-image']
KeyError: 'slither-docker-image'
`

**Comment by Henrykwokkk** [comment]
Excuse me. Did you solve the problem?

**Comment by mojtaba-eshghie** [comment]
Nope,
We are a team at KTH trying to use your tool for part of our research. If you could help running it we would appreciate.
Let me know your idea at eshghie@kth.se 
BR,

**Comment by pplllll** [comment]
> 

Excuse me. Did you solve the problem?
